export const hydrationLinks = [
  // '/lol/champions',
  // '/lol/tier-list',
  // '/lol/tier-list/high-elo',
  // '/lol/tier-list/stats',
  // '/lol/tier-list/aram',
  // '/lol/tier-list/arena-champions',
  // '/lol/tier-list/arena-synergies',
  // '/tft/tier-list/augments',
  // '/diablo-4/planner/builds',
  // '/poe-2/planner/builds',
  // '/poe/planner/builds',
  // '/borderlands-4/planner/builds',
  // '/deadlock/tier-list/heroes',
  // '/deadlock/tier-list/matchups',
  // '/deadlock/tier-list/synergies',
  // '/the-bazaar/planner/builds',
  // '/tft/team-comps',
  '/diablo-4/profile/cliptis',
  '/lol',
  '/lol/lp/profile',
  '/lol/glp/smart-highlights-1',
  '/lol/lp/gpi',
  '/tft',
  '/tft/lp/profile',
  '/tft/team-comps-tier-list',
  '/tft/community-comps',
  '/tft/my-comps',
  '/tft/champions',
  '/tft/unlockables',
  '/tft/items',
  '/tft/synergies/origins',
  '/tft/synergies/classes',
  '/tft/augments',
  '/tft/encounters',
  '/tft/tier-list/champions',
  '/tft/tier-list/traits',
  '/tft/comp-builder',
  '/tft/guides',
  '/diablo-4',
  '/diablo-4/profile',
  '/diablo-4/builds',
  '/diablo-4/tier-list',
  '/diablo-4/leveling-builds',
  '/diablo-4/guides',
  '/diablo-4/creators',
  '/diablo-4/interactive-map',
  '/poe-2',
  '/poe-2/profile',
  '/poe-2/tier-list',
  '/poe-2/starter-builds',
  '/poe-2/builds',
  '/poe-2/creators',
  '/poe-2/guides',
  '/poe',
  '/poe/profile',
  '/poe/tier-list',
  '/poe/starter-builds',
  '/poe/builds',
  '/poe/guides',
  '/destiny-2',
  '/destiny-2/lp/profile',
  '/destiny-2/build-planner',
  '/destiny-2/tier-list',
  '/destiny-2/weapons',
  '/destiny-2/builds',
  '/destiny-2/community-builds',
  '/borderlands-4',
  '/borderlands-4/profile',
  '/borderlands-4/tier-list',
  '/borderlands-4/vault-hunters',
  '/borderlands-4/builds',
  '/borderlands-4/creators',
  '/borderlands-4/guides/legendary-weapons-and-gear',
  '/borderlands-4/guides/shift-codes-borderlands-4',
  '/borderlands-4/guides',
  '/borderlands-4/wiki',
  '/hades-2',
  '/hades-2/profile',
  '/hades-2/planner/builds',
  '/hades-2/tier-list',
  '/hades-2/builds',
  '/hades-2/guides',
  '/hades-2/wiki',
  '/elden-ring-nightreign',
  '/elden-ring-nightreign/profile',
  '/elden-ring-nightreign/classes',
  '/elden-ring-nightreign/tier-list',
  '/elden-ring-nightreign/bosses',
  '/elden-ring-nightreign/guides',
  '/elden-ring-nightreign/wiki',
  '/deadlock',
  '/deadlock/player-profile',
  '/deadlock/classes',
  '/deadlock/tier-list/expert',
  '/deadlock/bosses',
  '/deadlock/guides',
  '/deadlock/builds',
  '/deadlock/build-stats',
  '/deadlock/items',
  '/valorant/maps',
  '/valorant/agents',
  '/valorant/map/all/guides',
  '/valorant/weapons',
  '/valorant/leaderboard',
  '/valorant/lp/profile',
  '/valorant/search',
  '/valorant/lesson-plan/master-valorant',
  '/mhw',
  '/mhw/profile',
  '/mhw/planner/builds',
  '/mhw/tier-list',
  '/mhw/builds',
  '/mhw/weapons',
  '/mhw/guides',
  '/mhw/monster-guides',
  '/the-bazaar',
  '/the-bazaar/profile',
  '/the-bazaar/tier-list',
  '/the-bazaar/builds',
  '/the-bazaar/community-builds',
  '/the-bazaar/heroes',
  '/the-bazaar/guides',
  '/the-bazaar/guides/pve-encounters-and-drops',
  '/the-bazaar/database/items-and-enchantments',
  '/the-bazaar/database/skills',
  '/the-bazaar/guides/meta-builds',
  '/marvel-rivals',
  '/marvel-rivals/profile',
  '/marvel-rivals/tier-list',
  '/marvel-rivals/heroes',
  '/marvel-rivals/guides',
  '/marvel-rivals/guides/best-team-ups',
  '/marvel-rivals/battle-matrix/home',
  '/zzz',
  '/zzz/profile',
  '/zzz/planner/builds',
  '/zzz/tier-list',
  '/zzz/builds',
  '/zzz/characters',
  '/zzz/teams',
  '/zzz/guides',
  '/zzz/bangboos',
  '/zzz/drive-discs',
  '/zzz/w-engines',
  '/news',
  '/news/goty-watch',
  '/news/release-calendar',
];
