const projectList = [
  {
    game: 'LoL',
    projectPath: '/lol',
    staticDataStPage: '/lol/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'Val',
    projectPath: '/valorant',
    staticDataStPage: '/valorant/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'TFT',
    projectPath: '/tft',
    staticDataStPage: '/tft/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'Riftbound',
    projectPath: '/riftbound',
    staticDataStPage: '/riftbound/qa-check-static-data-not-delete',
    features: {
      build: false,
      guide: true,
      tierList: true,
      team: false,
      deck: true,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: '2XKO',
    projectPath: '/2xko',
    staticDataStPage: '/2xko/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Marvel Rivals',
    projectPath: '/marvel-rivals',
    staticDataStPage: '/marvel-rivals/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'ZZZ',
    projectPath: '/zzz',
    staticDataStPage: '/zzz/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: true,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Diablo 4',
    projectPath: '/diablo-4',
    staticDataStPage: '/diablo-4/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Nightreign',
    projectPath: '/elden-ring-nightreign',
    staticDataStPage: '/elden-ring-nightreign/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Destiny 2',
    projectPath: '/destiny-2',
    staticDataStPage: '/destiny-2/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'Monster Hunter Wilds',
    projectPath: '/mhw',
    staticDataStPage: '/mhw/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Hades 2',
    projectPath: '/hades-2',
    staticDataStPage: '/hades-2/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Borderlands 4',
    projectPath: '/borderlands-4',
    staticDataStPage: '/borderlands-4/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Deadlock',
    projectPath: '/deadlock',
    staticDataStPage: '/deadlock/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'PoE 2',
    projectPath: '/poe-2',
    staticDataStPage: '/poe-2/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'PoE',
    projectPath: '/poe',
    staticDataStPage: '/poe/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'The Bazaar',
    projectPath: '/the-bazaar',
    staticDataStPage: '/the-bazaar/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Endfield',
    projectPath: '/arknights-endfield',
    staticDataStPage: '/arknights-endfield/qa-check-static-data-not-delete',
    features: {
      build: false,
      guide: true,
      tierList: true,
      team: true,
      deck: false,
      character: true,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Marathon',
    projectPath: '/marathon',
    staticDataStPage: '/marathon/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      character: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Overwatch',
    projectPath: '/overwatch',
    staticDataStPage: '/overwatch/qa-check-static-data-not-delete',
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      character: false,
      staticData: false,
      advertisement: true,
    },
  },
];

export const filterProjectsByFeatureStatus = (featureStatus) => {
  return projectList.filter((project) => project.features[featureStatus] === true);
};

// export const filterProjectsByFeatureStatus = (...featureStatuses) => {
//   return projectList.filter((project) => featureStatuses.some((status) => project.features[status] === true));
// };
