// const sitemapList = [
//   { linkInList: `${process.env.BASE_URL}/lol/tier-list`, isPresentInProdSitemap: true, pathUrl: '/product-sitemap.xml' },
//   { linkInList: `${process.env.BASE_URL}/valorant/maps`, isPresentInProdSitemap: true, pathUrl: '/valorant/sitemap.xml' },
//   { linkInList: `${process.env.BASE_URL}/post-sitemap.xml`, isPresentInProdSitemap: true, pathUrl: '/sitemap_index.xml' },
//   { linkInList: `${process.env.BASE_URL}/zzz`, isPresentInProdSitemap: true, pathUrl: '/zzz/sitemap.xml' },
//   {
//     linkInList: `${process.env.BASE_URL}/lol/champions/swain/build`,
//     isPresentInProdSitemap: true,
//     pathUrl: '/champions-sitemap.xml',
//   },
//   { linkInList: `${process.env.BASE_URL}/tft/tier-list/items`, isPresentInProdSitemap: true, pathUrl: '/tft/sitemap.xml' },
//   {
//     linkInList: `${process.env.BASE_URL}/tft/set16/items`,
//     isPresentInProdSitemap: true,
//     pathUrl: '/tft/set16/sitemap.xml',
//   },
//   { linkInList: `${process.env.BASE_URL}/destiny-2`, isPresentInProdSitemap: true, pathUrl: '/destiny-2/sitemap.xml' },
//   {
//     linkInList: `${process.env.BASE_URL}/example-game`,
//     isPresentInProdSitemap: false,
//     pathUrl: '/example-game/sitemap.xml',
//   },
//   { linkInList: `${process.env.BASE_URL}/diablo-4`, isPresentInProdSitemap: true, pathUrl: '/diablo-4/sitemap.xml' },
//   {
//     linkInList: `${process.env.BASE_URL}/elden-ring-nightreign`,
//     isPresentInProdSitemap: true,
//     pathUrl: '/elden-ring-nightreign/sitemap.xml',
//   },
//   {
//     linkInList: `${process.env.BASE_URL}/marvel-rivals`,
//     isPresentInProdSitemap: true,
//     pathUrl: '/marvel-rivals/sitemap.xml',
//   },
//   { linkInList: `${process.env.BASE_URL}/mhw`, isPresentInProdSitemap: true, pathUrl: '/mhw/sitemap.xml' },
//   { linkInList: `${process.env.BASE_URL}/hades-2`, isPresentInProdSitemap: true, pathUrl: '/hades-2/sitemap.xml' },
//   { linkInList: `${process.env.BASE_URL}/news`, isPresentInProdSitemap: true, pathUrl: '/news/sitemap.xml' },
//   {
//     linkInList: `${process.env.BASE_URL}/borderlands-4`,
//     isPresentInProdSitemap: true,
//     pathUrl: '/borderlands-4/sitemap.xml',
//   },
//   { linkInList: `${process.env.BASE_URL}/deadlock`, isPresentInProdSitemap: true, pathUrl: '/deadlock/sitemap.xml' },
//   { linkInList: `${process.env.BASE_URL}/poe-2`, isPresentInProdSitemap: true, pathUrl: '/poe-2/sitemap.xml' },
//   { linkInList: `${process.env.BASE_URL}/the-bazaar`, isPresentInProdSitemap: true, pathUrl: '/the-bazaar/sitemap.xml' },
//   { linkInList: `${process.env.BASE_URL}/poe`, isPresentInProdSitemap: true, pathUrl: '/poe/sitemap.xml' },
//   { linkInList: `${process.env.BASE_URL}/riftbound`, isPresentInProdSitemap: true, pathUrl: '/riftbound/sitemap.xml' },
//   { linkInList: `${process.env.BASE_URL}/2xko`, isPresentInProdSitemap: true, pathUrl: '/2xko/sitemap.xml' },
//   { linkInList: `${process.env.BASE_URL}/arknights-endfield`, isPresentInProdSitemap: true, pathUrl: '/arknights-endfield/sitemap.xml' },
// ];

const projectListFromSitemap = [
  { project: 'Set4-5', isPresentInProdSitemap: true, pathUrl: '/tft/set4-5/sitemap.xml' },
  { project: 'ZZZ', isPresentInProdSitemap: true, pathUrl: '/zzz/sitemap.xml' },
  { project: 'Example Game', isPresentInProdSitemap: false, pathUrl: '/example-game/sitemap.xml' },
  { project: 'Valorant', isPresentInProdSitemap: true, pathUrl: '/valorant/sitemap.xml' },
  { project: 'Sitemap Index', isPresentInProdSitemap: true, pathUrl: '/sitemap_index.xml' },
  { project: 'Product Sitemap', isPresentInProdSitemap: true, pathUrl: '/product-sitemap.xml' },
  { project: 'Sitemap', isPresentInProdSitemap: true, pathUrl: '/sitemap_index.xml' },
  { project: 'Champions', isPresentInProdSitemap: true, pathUrl: '/champions-sitemap.xml' },
  { project: 'TFT', isPresentInProdSitemap: true, pathUrl: '/tft/sitemap.xml' },
  { project: 'Set15', isPresentInProdSitemap: true, pathUrl: '/tft/set16/sitemap.xml' },
  { project: 'Destiny 2', isPresentInProdSitemap: true, pathUrl: '/destiny-2/sitemap.xml' },
  { project: 'Diablo 4', isPresentInProdSitemap: true, pathUrl: '/diablo-4/sitemap.xml' },
  { project: 'Nightreign', isPresentInProdSitemap: true, pathUrl: '/elden-ring-nightreign/sitemap.xml' },
  { project: 'Marvel Rivals', isPresentInProdSitemap: true, pathUrl: '/marvel-rivals/sitemap.xml' },
  { project: 'Monster Hunter Wilds', isPresentInProdSitemap: true, pathUrl: '/mhw/sitemap.xml' },
  { project: 'Hades 2', isPresentInProdSitemap: true, pathUrl: '/hades-2/sitemap.xml' },
  { project: 'News', isPresentInProdSitemap: true, pathUrl: '/news/sitemap.xml' },
  { project: 'Borderlands 4', isPresentInProdSitemap: true, pathUrl: '/borderlands-4/sitemap.xml' },
  { project: 'Deadlock', isPresentInProdSitemap: true, pathUrl: '/deadlock/sitemap.xml' },
  { project: 'PoE 2', isPresentInProdSitemap: true, pathUrl: '/poe-2/sitemap.xml' },
  { project: 'The Bazaar', isPresentInProdSitemap: true, pathUrl: '/the-bazaar/sitemap.xml' },
  { project: 'PoE', isPresentInProdSitemap: true, pathUrl: '/poe/sitemap.xml' },
  { project: 'Riftbound', isPresentInProdSitemap: true, pathUrl: '/riftbound/sitemap.xml' },
  { project: '2XKO', isPresentInProdSitemap: true, pathUrl: '/2xko/sitemap.xml' },
  { project: 'Endfield', isPresentInProdSitemap: true, pathUrl: '/arknights-endfield/sitemap.xml' },
  { project: 'Marathon', isPresentInProdSitemap: false, pathUrl: '/marathon/sitemap.xml' },
  { project: 'Overwatch', isPresentInProdSitemap: false, pathUrl: '/overwatch/sitemap.xml' },
];

export { projectListFromSitemap };
