const projectList = [
  {
    game: 'LoL',
    projectPath: '/lol',
    staticData: {
      staticDataStPage: '/lol/qa-check-static-data-not-delete',
    },
    features: {
      classic: true,
      build: false,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'Val',
    projectPath: '/valorant',
    staticData: {
      staticDataStPage: '/valorant/qa-check-static-data-not-delete',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'TFT',
    projectPath: '/tft',
    staticData: {
      staticDataStPage: '/tft/qa-check-static-data-not-delete',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'Riftbound',
    projectPath: '/riftbound',
    staticData: {
      staticDataStPage: '/riftbound/qa-check-static-data-not-delete',
      gameSpecificItem: 'Acceleration Gate',
    },
    features: {
      build: false,
      guide: true,
      tierList: true,
      team: false,
      deck: true,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: '2XKO',
    projectPath: '/2xko',
    staticData: {
      staticDataStPage: '/2xko/qa-check-static-data-not-delete',
      gameSpecificItem: 'Blitzcrank',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Marvel Rivals',
    projectPath: '/marvel-rivals',
    staticData: {
      staticDataStPage: '/marvel-rivals/qa-check-static-data-not-delete',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'ZZZ',
    projectPath: '/zzz',
    staticData: {
      staticDataStPage: '/zzz/qa-check-static-data-not-delete',
      gameSpecificItem: 'Alice',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: true,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Diablo 4',
    projectPath: '/diablo-4',
    staticData: {
      staticDataStPage: '/diablo-4/qa-check-static-data-not-delete',
      gameSpecificItem: 'Amethyst',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Nightreign',
    projectPath: '/elden-ring-nightreign',
    staticData: {
      staticDataStPage: '/elden-ring-nightreign/qa-check-static-data-not-delete',
      gameSpecificItem: 'Blood Loss',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    //* Waiting for when Destiny 2 will be integrated into MGP
    game: 'Destiny 2',
    projectPath: '/destiny-2',
    staticData: {
      staticDataStPage: '/destiny-2/qa-check-static-data-not-delete',
      gameSpecificItem: 'item',
    },
    features: {
      build: false,
      guide: false,
      tierList: false,
      team: false,
      deck: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'Monster Hunter Wilds',
    projectPath: '/mhw',
    staticData: {
      staticDataStPage: '/mhw/qa-check-static-data-not-delete',
      gameSpecificItem: 'Dragon',
      exactMatch: true,
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'NTE',
    projectPath: '/neverness-to-everness',
    staticData: {
      staticDataStPage: '/neverness-to-everness/qa-check-static-data-not-delete',
      gameSpecificItem: 'Adler',
      exactMatch: true,
    },
    features: {
      character: true,
      build: false,
      guide: true,
      tierList: true,
      team: true,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Genshin',
    projectPath: '/genshin-impact',
    staticData: {
      staticDataStPage: '/genshin-impact/qa-check-static-data-not-delete',
      gameSpecificItem: 'ATK',
      exactMatch: true,
    },
    features: {
      character: true,
      build: false,
      guide: true,
      tierList: true,
      team: true,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Hades 2',
    projectPath: '/hades-2',
    staticData: {
      staticDataStPage: '/hades-2/qa-check-static-data-not-delete',
      gameSpecificItem: 'Frinos',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Borderlands 4',
    projectPath: '/borderlands-4',
    staticData: {
      staticDataStPage: '/borderlands-4/qa-check-static-data-not-delete',
      gameSpecificItem: 'Entanglement',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Deadlock',
    projectPath: '/deadlock',
    staticData: {
      staticDataStPage: '/deadlock/qa-check-static-data-not-delete',
      gameSpecificItem: 'Alchemical Fire',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'PoE 2',
    projectPath: '/poe-2',
    staticData: {
      staticDataStPage: '/poe-2/qa-check-static-data-not-delete',
      gameSpecificItem: 'Acolyte of Chayula',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'PoE',
    projectPath: '/poe',
    staticData: {
      staticDataStPage: '/poe/qa-check-static-data-not-delete',
      gameSpecificItem: 'Ascendant',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'The Bazaar',
    projectPath: '/the-bazaar',
    staticData: {
      staticDataStPage: '/the-bazaar/qa-check-static-data-not-delete',
      gameSpecificItem: 'Dooley',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Endfield',
    projectPath: '/arknights-endfield',
    staticData: {
      staticDataStPage: '/arknights-endfield/qa-check-static-data-not-delete',
      gameSpecificItem: 'Akekuri',
    },
    features: {
      build: false,
      guide: true,
      tierList: true,
      team: true,
      deck: false,
      character: true,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Marathon',
    projectPath: '/marathon',
    staticData: {
      staticDataStPage: '/marathon/qa-check-static-data-not-delete',
      gameSpecificItem: 'Light Rounds',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      character: false,
      staticData: true,
      advertisement: true,
    },
  },
  {
    game: 'Overwatch',
    projectPath: '/overwatch',
    staticData: {
      staticDataStPage: '/overwatch/qa-check-static-data-not-delete',
      gameSpecificItem: 'Light Rounds',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      character: false,
      staticData: false,
      advertisement: true,
    },
  },
  {
    game: 'STS 2',
    projectPath: '/slay-the-spire-2',
    staticData: {
      staticDataStPage: '/slay-the-spire-2/qa-check-static-data-not-delete',
      gameSpecificItem: 'Defect',
    },
    features: {
      build: true,
      guide: true,
      tierList: true,
      team: false,
      deck: false,
      character: false,
      staticData: true,
      advertisement: true,
    },
  },
];

export const filterProjectsByFeatureStatus = (featureStatus) => {
  return projectList.filter((project) => project.features[featureStatus] === true);
};

// export const filterProjectsByFeatureStatus = (...featureStatuses) => {
//   return projectList.filter((project) => featureStatuses.some((status) => project.features[status] === true));
// };
