export const projectListFromSitemap = [
  { project: 'ZZZ', isPresentInProdSitemap: true, pathUrl: '/zzz/sitemap.xml' },
  { project: 'Example Game', isPresentInProdSitemap: false, pathUrl: '/example-game/sitemap.xml' },
  { project: 'Valorant', isPresentInProdSitemap: true, pathUrl: '/valorant/sitemap.xml' },
  { project: 'Sitemap Index', isPresentInProdSitemap: true, pathUrl: '/sitemap_index.xml' },
  { project: 'Product Sitemap', isPresentInProdSitemap: true, pathUrl: '/product-sitemap.xml' },
  { project: 'Sitemap', isPresentInProdSitemap: true, pathUrl: '/sitemap_index.xml' },
  { project: 'Champions', isPresentInProdSitemap: true, pathUrl: '/champions-sitemap.xml' },
  { project: 'TFT', isPresentInProdSitemap: true, pathUrl: '/tft/sitemap.xml' },
  { project: 'Set17', isPresentInProdSitemap: true, pathUrl: '/tft/set17/sitemap.xml' },
  { project: 'Destiny 2', isPresentInProdSitemap: true, pathUrl: '/destiny-2/sitemap.xml' },
  { project: 'Diablo 4', isPresentInProdSitemap: true, pathUrl: '/diablo-4/sitemap.xml' },
  { project: 'Nightreign', isPresentInProdSitemap: true, pathUrl: '/elden-ring-nightreign/sitemap.xml' },
  { project: 'Marvel Rivals', isPresentInProdSitemap: true, pathUrl: '/marvel-rivals/sitemap.xml' },
  { project: 'Monster Hunter Wilds', isPresentInProdSitemap: true, pathUrl: '/mhw/sitemap.xml' },
  { project: 'Hades 2', isPresentInProdSitemap: true, pathUrl: '/hades-2/sitemap.xml' },
  { project: 'Borderlands 4', isPresentInProdSitemap: true, pathUrl: '/borderlands-4/sitemap.xml' },
  { project: 'Deadlock', isPresentInProdSitemap: true, pathUrl: '/deadlock/sitemap.xml' },
  { project: 'PoE 2', isPresentInProdSitemap: true, pathUrl: '/poe-2/sitemap.xml' },
  { project: 'The Bazaar', isPresentInProdSitemap: true, pathUrl: '/the-bazaar/sitemap.xml' },
  { project: 'PoE', isPresentInProdSitemap: true, pathUrl: '/poe/sitemap.xml' },
  { project: 'Riftbound', isPresentInProdSitemap: true, pathUrl: '/riftbound/sitemap.xml' },
  { project: '2XKO', isPresentInProdSitemap: true, pathUrl: '/2xko/sitemap.xml' },
  { project: 'Endfield', isPresentInProdSitemap: true, pathUrl: '/arknights-endfield/sitemap.xml' },
  { project: 'Marathon', isPresentInProdSitemap: true, pathUrl: '/marathon/sitemap.xml' },
  { project: 'Overwatch', isPresentInProdSitemap: true, pathUrl: '/overwatch/sitemap.xml' },
  { project: 'STS2', isPresentInProdSitemap: true, pathUrl: '/slay-the-spire-2/sitemap.xml' },
  { project: 'Genshin', isPresentInProdSitemap: true, pathUrl: '/genshin-impact/sitemap.xml' },
  { project: 'Set 17', isPresentInProdSitemap: true, pathUrl: '/tft/set17/sitemap.xml' },
  { project: 'Set 18', isPresentInProdSitemap: true, pathUrl: '/tft/set18/sitemap.xml' },
  { project: 'Gamebase', isPresentInProdSitemap: true, pathUrl: '/gamebase/sitemap.xml' },
];
